[package]
name = "informalsystems-malachitebft-core-votekeeper"
description = "Voting system for the Malachite BFT consensus engine"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[package.metadata.docs.rs]
all-features = true

[dependencies]
malachitebft-core-types = { workspace = true }

derive-where = { workspace = true }
thiserror = { workspace = true, default-features = false }

[dev-dependencies]
malachitebft-test = { workspace = true }
